name: cht_observations

channels:
  - conda-forge

dependencies:
  - black
  - build
  - geopandas
  - mypy
  - pip
  - pip:
    - NDBC
    - noaa_coops
  - pytest
  - python=3.10
  - shapely
  - twine
